const EXCHANGE_BITMEX = 'bitmex'
const EXCHANGE_UPBIT = 'upbit'
const SUPPORTABLE_EXCHANGES = [EXCHANGE_BITMEX]
const ENABLE_TEST_EXCHANGES = [EXCHANGE_BITMEX]

module.exports = {
    EXCHANGE_BITMEX,
    EXCHANGE_UPBIT,
    SUPPORTABLE_EXCHANGES,
    ENABLE_TEST_EXCHANGES
}