FROM mariadb:10.5

ENV MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
ENV MARIADB_DATABASE=cats
ENV MARIADB_USER=cats
ENV MARIADB_PASSWORD=cats

ADD https://raw.githubusercontent.com/Seungwoo321/cats/master/dockerfiles/entry-mariadb.sql /docker-entrypoint-initdb.d/

EXPOSE 3306